# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore,  QtWidgets
from PyQt6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,QAction,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PyQt6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QHeaderView,
    QLabel, QListWidget, QListWidgetItem, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)
from PyQt6.QtWebEngineWidgets import QWebEngineView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")


        self.folderSelectButton = QPushButton(self.centralwidget)
        self.folderSelectButton.setObjectName(u"folderSelectButton")
        self.horizontalLayout.addWidget(self.folderSelectButton)

        self.previousButton = QPushButton(self.centralwidget)
        self.previousButton.setObjectName(u"previousButton")
        self.horizontalLayout.addWidget(self.previousButton)

        self.nextButton = QPushButton(self.centralwidget)
        self.nextButton.setObjectName(u"nextButton")
        self.horizontalLayout.addWidget(self.nextButton)

        self.applyPreviousButton = QPushButton(self.centralwidget)
        self.applyPreviousButton.setObjectName(u"applyPreviousButton")
        self.horizontalLayout.addWidget(self.applyPreviousButton)

        self.SaveButton = QPushButton(self.centralwidget)
        self.SaveButton.setObjectName(u"SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)

        self.googleTakeOutButton = QPushButton(self.centralwidget)
        self.googleTakeOutButton.setObjectName(u"googleTakeOutButton")
        self.horizontalLayout.addWidget(self.googleTakeOutButton)

        self.clearGoogleTakeOutButton = QPushButton(self.centralwidget)
        self.clearGoogleTakeOutButton.setObjectName(u"clearGoogleTakeOutButton")
        self.horizontalLayout.addWidget(self.clearGoogleTakeOutButton)



        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")


        self.fileListWidget = QListWidget(self.centralwidget)
        self.fileListWidget.setObjectName(u"fileListWidget")
        self.fileListWidget.setMaximumSize(300, 60000)
        self.horizontalLayout_2.addWidget(self.fileListWidget)


        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")


        self.imageViewWidget = QtWidgets.QLabel(parent=self.centralwidget)
        self.imageViewWidget.setScaledContents(True)
        self.imageViewWidget.setMaximumSize(600, 400)
        self.imageViewWidget.setMinimumSize(519,251)
        self.imageViewWidget.setObjectName("imageViewWidget")
        self.verticalLayout_3.addWidget(self.imageViewWidget,alignment=Qt.AlignmentFlag.AlignCenter)
        

        self.mapViewWidget = QWebEngineView(parent=self.centralwidget)
        self.mapViewWidget.setGeometry(QtCore.QRect(310, 300, 471, 251))
        self.verticalLayout_3.addWidget(self.mapViewWidget)
        self.create_mapHTLM()


        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.gpsFilesListWidget = QTreeWidget(self.centralwidget)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"Takeout Files");
        self.gpsFilesListWidget.setHeaderItem(__qtreewidgetitem)
        self.gpsFilesListWidget.setObjectName(u"gpsFilesListWidget")
        self.gpsFilesListWidget.setMaximumSize(300, 60000)
        self.horizontalLayout_2.addWidget(self.gpsFilesListWidget)

        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 2, 1, 1)


        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")

        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName(u"Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
        # setupUi



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Photo Location Updater"))
        self.nextButton.setText(_translate("MainWindow", ">"))
        self.applyPreviousButton.setText(_translate("MainWindow", "Apply Previous"))
        self.folderSelectButton.setText(_translate("MainWindow", "Select Folder"))
        self.previousButton.setText(_translate("MainWindow", "<"))
        self.SaveButton.setText(_translate("MainWindow", "Save and next"))
        self.googleTakeOutButton.setText(_translate("MainWindow", u"Google Takout Location", None))
        self.clearGoogleTakeOutButton.setText(_translate("MainWindow", u"Clear Google Takout", None))
        
        self.menuHelp.setTitle(QtCore.QCoreApplication.translate("MainWindow", u"Help", None))
        self.actionAbout.setText(QtCore.QCoreApplication.translate("MainWindow", u"About", None))
       

    def create_mapHTLM(self):
        """
        Creates an HTML template for a Leaflet map.
        Returns:
        str: The HTML template for the Leaflet map.
        """

        with open("map.html", "r") as file:
            htmlFromFile = file.read()

        
        # Set the HTML content to the mapViewWidget
        self.mapViewWidget.setHtml(htmlFromFile)